#pragma once

#include <cstdint>
#include <functional>
#include <optional>

#include "goreecloud/browser/media_target_detector.hpp"

namespace goreecloud::browser {

struct MediaHitTestPoint {
  int viewport_x{0};
  int viewport_y{0};
};

class MediaHitTestProvider {
 public:
  virtual ~MediaHitTestProvider() = default;

  [[nodiscard]] virtual std::optional<EngineMediaHitTest> media_hit_test(
      MediaHitTestPoint point) const = 0;
};

class AsyncMediaHitTestProvider {
 public:
  using ResultCallback =
      std::function<void(std::uint64_t sequence,
                         std::optional<EngineMediaHitTest> result)>;

  virtual ~AsyncMediaHitTestProvider() = default;

  // The sequence value is generated by the caller and must be echoed in the
  // response. Callers reject responses older than their most recent request.
  virtual bool request_media_hit_test(MediaHitTestPoint point,
                                      std::uint64_t sequence,
                                      ResultCallback callback) = 0;
};

// EngineView implementations may optionally implement either provider.
// Browser code discovers them through dynamic_cast and keeps CEF/Chromium
// types behind the engine adapter boundary.
inline constexpr bool kMediaHitTestingIsEngineOptionalCapability = true;
inline constexpr bool kAsyncMediaHitTestingSupportsStaleResultRejection = true;
static_assert(kMediaHitTestingIsEngineOptionalCapability);
static_assert(kAsyncMediaHitTestingSupportsStaleResultRejection);

}  // namespace goreecloud::browser
